sudo: false
dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "7"
  - "8"
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp-cli
script: gulp build
