stc.modal.i18n = {
    "default": {
        "title": "Welcome to Save the Children!",
        "text": "You've come to our Swiss site, which contains information about our work with children around the world. You can also visit our {country} site to explore the different ways you can support our work.",
        "stayBtn": "Stay on the Swiss website",
        "goBtn": "Go to {country} site",
        "countries": {
            "AU": "Australia",
            "CA": "Canada",
            "CO": "Colombia",
            "DK": "Denmark",
            "DO": "Dominican Republic",
            "FJ": "Fiji",
            "FI": "Finland",
            "DE": "Germany",
            "GT": "Guatemala",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IT": "Italy",
            "JP": "Japan",
            "KR": "Korea",
            "LT": "Lithuania",
            "MX": "Mexico",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NO": "Norway",
            "PH": "Philippines",
            "RO": "Romania",
            "ZA": "South Africa",
            "ES": "Spain",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "CH": "Switzerland",
            "GB": "UK",
            "US": "U.S.",
            "XX": "International"
        }
    },
    "de": {
        "title": "Willkommen auf Save the Children!",
        "text": "You've come to our Swiss site, which contains information about our work with children around the world. You can also visit our {country} site to explore the different ways you can support our work.",
        "stayBtn": "Stay on the Swiss website",
        "goBtn": "Go to {country} site",
        "countries": {
            "AU": "Australia",
            "CA": "Canada",
            "CO": "Colombia",
            "DK": "Denmark",
            "DO": "Dominican Republic",
            "FJ": "Fiji",
            "FI": "Finland",
            "DE": "Germany",
            "GT": "Guatemala",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IT": "Italy",
            "JP": "Japan",
            "KR": "Korea",
            "LT": "Lithuania",
            "MX": "Mexico",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NO": "Norway",
            "PH": "Philippines",
            "RO": "Romania",
            "ZA": "South Africa",
            "ES": "Spain",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "CH": "Switzerland",
            "GB": "UK",
            "US": "U.S.",
            "XX": "International"
        }
    },
    "fr": {
        "title": "Bienvenue chez Save the Children!",
        "text": "Vous semblez &ecirc;tre en {country}.",
        "stayText": "Ou Restez sur le site suisse.",
        "prefix": "",
        "goBtn": "Continuez vers {country}",
        "countries": {
            "AU": "Australia",
            "CA": "Canada",
            "CO": "Colombia",
            "DK": "Denmark",
            "DO": "Dominican Republic",
            "FJ": "Fiji",
            "FI": "Finland",
            "DE": "Germany",
            "GT": "Guatemala",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IT": "Italy",
            "JP": "Japan",
            "KR": "Korea",
            "LT": "Lithuania",
            "MX": "Mexico",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NO": "Norway",
            "PH": "Philippines",
            "RO": "Romania",
            "ZA": "South Africa",
            "ES": "Spain",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "CH": "Switzerland",
            "GB": "Grande-Bretagne",
            "US": "U.S.A.",
            "XX": "International"
        }
    },
    "it": {
        "title": "Benvenuti a Save the Children!",
        "text": "You've come to our Swiss site, which contains information about our work with children around the world. You can also visit our {country} site to explore the different ways you can support our work.",
        "stayBtn": "Stay on the Swiss website",
        "goBtn": "Go to {country} site",
        "countries": {
            "AU": "Australia",
            "CA": "Canada",
            "CO": "Colombia",
            "DK": "Denmark",
            "DO": "Dominican Republic",
            "FJ": "Fiji",
            "FI": "Finland",
            "DE": "Germany",
            "GT": "Guatemala",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IT": "Italy",
            "JP": "Japan",
            "KR": "Korea",
            "LT": "Lithuania",
            "MX": "Mexico",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NO": "Norway",
            "PH": "Philippines",
            "RO": "Romania",
            "ZA": "South Africa",
            "ES": "Spain",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "CH": "Switzerland",
            "GB": "UK",
            "US": "U.S.",
            "XX": "International"
        }
    }
};
