stc.modal.i18n = {
    default: {
        title: 'Welcome to <nobr>Save the Children</nobr>!',
        text: 'It looks like you\'re in {country}',
        stayText: 'Or <a href="javascript:stc.modal.close(\'Stay\');">stay on the U.S. website</a> to find additional information about the work that we do here in the U.S.',
        goBtn: 'Continue to {country}',
        prefix: 'the ',
        countries: {
            AU: 'Australia',
            CA: 'Canada',
            CO: 'Colombia',
            DK: 'Denmark',
            DO: 'Dominican Republic',
            FJ: 'Fiji',
            FI: 'Finland',
            DE: 'Germany',
            GT: 'Guatemala',
            HN: 'Honduras',
            HK: 'Hong Kong',
            IS: 'Iceland',
            IN: 'India',
            ID: 'Indonesia',
            IT: 'Italy',
            JP: 'Japan',
            KR: 'Korea',
            LT: 'Lithuania',
            MX: 'Mexico',
            NL: 'Netherlands',
            NZ: 'New Zealand',
            NO: 'Norway',
            PH: 'Philippines',
            RO: 'Romania',
            ZA: 'South Africa',
            ES: 'Spain',
            SZ: 'Swaziland',
            SE: 'Sweden',
            CH: 'Switzerland',
            GB: 'UK',
            US: 'U.S.',
            XX: 'International',
        },
    },
};
