stc.modal.i18n = {
    default: {
        title: 'Welcome to <span class="text-nowrap">Save the Children</span>!',
        text: 'Here you’ll find news and information on our global organisation and the work we do for children around the world. You can also visit your local Save the Children {country} website to learn more about how you can support our work.',
        stayBtn: 'Stay on International site',
        stayText: 'Or <a href="javascript:stc.modal.close(\'Stay\');">stay here</a> to find additional information about our global organization and the work that <span class="text-nowrap">we do</span>.',
        goBtn: 'Go to {country} site',
        prefix: 'the ',
        countries: {
            AU: 'Australia',
            CA: 'Canada',
            CO: 'Colombia',
            DK: 'Denmark',
            DO: 'Dominican Republic',
            FJ: 'Fiji',
            FI: 'Finland',
            DE: 'Germany',
            GT: 'Guatemala',
            HN: 'Honduras',
            HK: 'Hong Kong',
            IS: 'Iceland',
            IN: 'India',
            ID: 'Indonesia',
            IT: 'Italy',
            JP: 'Japan',
            KR: 'Korea',
            LT: 'Lithuania',
            MX: 'Mexico',
            NL: 'Netherlands',
            NZ: 'New Zealand',
            NO: 'Norway',
            PH: 'Philippines',
            RO: 'Romania',
            ZA: 'South Africa',
            ES: 'Spain',
            SZ: 'Swaziland',
            SE: 'Sweden',
            CH: 'Switzerland',
            GB: 'UK',
            US: 'U.S.',
            XX: 'International',
        },
    },
}
