stc.modal.i18n = {
    "default": {
        "title": "Welcome to Save the Children International!",
        "text": "Here you'll find information on our global organization and the work we do for children around the world. You can also visit Save the Children {country} to learn more about what we do and support <nobr>our work</nobr>.",
        "stayBtn": "Stay on this site",
        "goBtn": "Go to {country} site",
        "countries": {
            "AU": "Australia",
            "CA": "Canada",
            "CO": "Colombia",
            "DK": "Denmark",
            "DO": "Dominican Republic",
            "FJ": "Fiji",
            "FI": "Finland",
            "DE": "Germany",
            "GT": "Guatemala",
            "HN": "Honduras",
            "HK": "Hong Kong",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IT": "Italy",
            "JP": "Japan",
            "KR": "Korea",
            "LT": "Lithuania",
            "MX": "Mexico",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NO": "Norway",
            "PH": "Philippines",
            "RO": "Romania",
            "ZA": "South Africa",
            "ES": "Spain",
            "SZ": "Swaziland",
            "SE": "Sweden",
            "CH": "Switzerland",
            "GB": "UK",
            "US": "U.S.",
            "XX": "International"
        }
    }
};
